modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Plague Core"
description = '''Ядро чумы: прогрессирующее заражение мира.'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

# Голос больного. Необязательно: без голосового чата мод грузится как обычно.
[[dependencies.${mod_id}]]
modId = "voicechat"
type = "optional"
versionRange = "[2.6,)"
ordering = "NONE"
side = "BOTH"
